name: remote ssh command
on: [push]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /usr/projects/FitnessApp_Backend
          git pull origin main
          docker image prune -a -f
          docker-clean
          docker builder prune --force
          docker-compose build --no-cache
          docker-compose down
          docker-compose up -d
